// app/images.ts
export const images = [
  {
    id: 1,
    name: "Demo",
    images: [
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/e03/pano/1.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/e03/pano/2.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/e03/pano/3.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/e03/pano/4.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/e03/pano/5.webp",
    ],
  },
  {
    id: 2,
    name: "Logo",
    images: [
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/logo/1+-+AC+-+Abstergo_logo.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/logo/2+-+resident+Evil+-+Umbrella_Corporation.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/logo/3+-+Portal+-+Aperture_Science.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/logo/4+-+Fallout+4+-+Vault-Tec+.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/logo/5+-+SCP_Foundation.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/logo/6+-+transistor+camerata.webp",
    ],
  },
  {
    id: 3,
    name: "Bob - Main Menu",
    images: [
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/lennon/1-1.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/lennon/1-2.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/lennon/1-3.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/lennon/1-4.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/lennon/1-5.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/lennon/1-6.webp",
    ],
  },
  {
    id: 4,
    name: "Marcus - Main Menu",
    images: [
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/marcus/1-1.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/marcus/1-2.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/marcus/1-3.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/marcus/1-4.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/marcus/1-5.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/marcus/1-6.webp",
    ],
  },
  {
    id: 5,
    name: "Main Menu 1",
    images: [
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-1/1-1.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-1/1-2.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-1/1-3.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-1/1-4.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-1/1-5.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-1/1-6.webp",
    ],
  },
  {
    id: 6,
    name: "Main Menu 2",
    images: [
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-2/1-1.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-2/1-2.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-2/1-3.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-2/1-4.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-2/1-5.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/menu-2/1-6.webp",
    ],
  },
  {
    id: 7,
    name: "Loading 1",
    images: [
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-1/1-1.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-1/1-2.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-1/1-3.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-1/1-4.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-1/1-5.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-1/1-6.webp",
    ],
  },
  {
    id: 8,
    name: "Loading 2",
    images: [
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-2/1-1.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-2/1-2.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-2/1-3.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-2/1-4.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-2/1-5.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-2/1-6.webp",
    ],
  },
  {
    id: 9,
    name: "Loading 3",
    images: [
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-3/1-1.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-3/1-2.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-3/1-3.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-3/1-4.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-3/1-5.webp",
      "https://red-bull-checkpoint.s3.eu-west-3.amazonaws.com/geogamer-shorts/e06-e07-shorts/loading-3/1-6.webp",
    ],
  },
];
